theme:
    name: material

site_name: Parametrix
site_description: The documentation for the Parametrix software library.
site_author: Gabriel S. Gerlero
site_url: https://parametrix.readthedocs.io/

repo_url: https://github.com/gerlero/parametrix
repo_name: gerlero/parametrix

strict: true

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_if_no_docstring: true
                    show_root_heading: true
                    show_signature_annotations: true
                    show_symbol_type_toc: true


nav:
    - 'index.md'
